name: The Reusable Deploy Workflow

# Set the following GitHub Secrets:
#    SERVER_HOST – the IP or domain of your server
#    SERVER_USER – the username for SSH
#    SERVER_PASSWORD – password (or switch to using key for SSH key-based auth)
#    SERVER_PORT – typically 22
#    SERVER_TARGET – the path on the server where the files should go

on:
  workflow_call:
    inputs:
      onlyNewer:
        description: 'Only transfer files that are newer than the ones on the remote server'
        required: true
        type: string
      options:
        description: 'Any additional mirror command options to configure'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: dist/
      - name: Deploy static files via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          # SFTP credentials
          host: ${{ vars.SERVER_HOST }}
          port: ${{ vars.SERVER_PORT }}
          user: ${{ vars.SERVER_USER }}
          pass: ${{ secrets.SERVER_PASSWORD }}
          fingerprint: 'ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEA2zJZx6VkSJC14SILqvzLiR3v8eS0D7Zs7C7771yDwa90UW8JkhK23dk/G8R74kdcWYEOn3kCSr/2rz+UtYThZeWUa5F6BcT/X5Gwh1RAlw5ESxnRr+hiZhYLI7BivVIo5EzecIs0KEojMRUkXI+ClHIcyXBY6grflQFgjZphFMs='
          # lftp settings
          onlyNewer: ${{ env.onlyNewer }}
          restoreMTime: 'false'
          parallel: '3'
          # Mirror command options
          localDir: './dist/'
          remoteDir: ${{ vars.SERVER_TARGET }}
          options: ${{ env.options }}
